#!/bin/sh
#
# spaceman-diff
# ...because you're too busy to leave the command line, dammit.
#
# Enjoy.

set -e

filename=`basename $1`
extension=${filename##*.}

screenWidth=$(stty size | cut -d " " -f2)
screenWidthMinusBuffer=$(expr $screenWidth - 4)
perDiffWidth=$(expr $screenWidthMinusBuffer / 2)

fileA=$2
fileB=$5

case "$extension" in
  "jpg"|"jpeg"|"gif"|"png")
    outputA=`jp2a $fileA --color --width=$perDiffWidth`
    outputB=`jp2a $fileB --color --width=$perDiffWidth`

    lengthA=`echo "$outputA" | wc -l | xargs`
    lengthB=`echo "$outputB" | wc -l | xargs`
    max=`echo "$lengthA\n$lengthB" | sort -r | head -n1`

    for (( i=1; i<=$max; i++ ))
    do
      A=$(echo "$outputA" | sed -n ${i}p)
      B=$(echo "$outputB" | sed -n ${i}p)

      if [ "$A" = "" ] ; then
        A=$(yes " " | head -n$perDiffWidth | tr -d '\n')
      fi

      if [ "$B" = "" ] ; then
        B=$(yes " " | head -n$perDiffWidth | tr -d '\n')
      fi

      echo "$A""    ""$B"
    done
  ;;
  *)
    # Fallback to Git's own diffing
    git diff --no-ext-diff
  ;;
esac
