#!/bin/sh
#
# spaceman-diff
# ...because you're too busy to leave the command line, dammit.
#
# Enjoy.

set -e

filename=`basename $1`
extension=${filename##*.}

screenWidth=$(stty size | cut -d " " -f2)
screenWidthMinusBuffer=$(expr $screenWidth - 4)
perDiffWidth=$(expr $screenWidthMinusBuffer / 2)

fileA=$2
fileB=$5

case "$extension" in
  "jpg"|"jpeg"|"gif"|"png")
    outputA=`convert $fileA jpg:- | jp2a --color --width=$perDiffWidth -`
    outputB=`convert $fileB jpg:- | jp2a --color --width=$perDiffWidth -`

    lengthA=`echo "$outputA" | wc -l | xargs`
    lengthB=`echo "$outputB" | wc -l | xargs`
    max=`echo "$lengthA\n$lengthB" | sort -nr | head -n1`

    sizeA=$(ls -lh $fileA | cut -d" " -f9)
    sizeB=$(ls -lh $fileB | cut -d" " -f9)
    echo "Filesize A: $sizeA, Filesize B: $sizeB"

    for (( i=1; i<=$max; i++ ))
    do
      A=$(echo "$outputA" | sed -n ${i}p)
      B=$(echo "$outputB" | sed -n ${i}p)

      if [ "$A" = "" ] ; then
        A=$(yes " " | head -n$perDiffWidth | tr -d '\n')
      fi

      if [ "$B" = "" ] ; then
        B=$(yes " " | head -n$perDiffWidth | tr -d '\n')
      fi

      echo "$A    $B"
    done
  ;;
  *)
    # Fallback to Git's own diffing
    git diff --no-ext-diff
  ;;
esac
